# Generated by Django 4.2 on 2023-05-14 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0007_alter_selections_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selections',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 1, 5, 37, 189095), verbose_name='Время'),
        ),
    ]
