# Generated by Django 4.2 on 2023-05-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods_selection_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='selection_id',
        ),
    ]
