# Generated by Django 4.2 on 2023-05-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_selection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.CharField(max_length=10000, null=True, verbose_name='Цена'),
        ),
    ]
